### PR TITLE
Whitespaces

### PR DESCRIPTION
**Pull request by coleenp**
I have a vi macro that strips out whitespaces so the change I'm doing looks like a lot more changes than I have.  This pull request is to fix the trailing whitespaces.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/37/head:pull/37` \
`$ git checkout pull/37`

Update a local copy of the PR: \
`$ git checkout pull/37` \
`$ git pull https://git.openjdk.java.net/loom pull/37/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 37`

View PR using the GUI difftool: \
`$ git pr show -t 37`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/37.diff">https://git.openjdk.java.net/loom/pull/37.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Easy to review :)

**Comment by coleenp** [comment]
Thanks Thomas!  I might need a sponsor, will find out what happens next.

**Comment by tstuefe** [comment]
Oh, this is Loom, I misread your mail. The missing JBS link should have tripped me off. 

Since I am no Loom reviewer you'll need a real Loom person to review this again. Sorry for the confusion.

**Pull request closed without merging**
