### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by Glusk**
---------
### Progress
- [x] Change must not contain extraneous whitespace

### Errors
&nbsp;⚠️ OCA signatory status must be verified
&nbsp;⚠️ The pull request body must not be empty.

### Download
`$ git fetch https://git.openjdk.java.net/loom pull/28/head:pull/28`
`$ git checkout pull/28`

### CODE REVIEW

**Comment by AlanBateman** [comment]
I assume this PR has been abandoned, I'll close it in a few days if there isn't any update.

**Comment by Glusk** [comment]
@AlanBateman
I mean, abandoned...

I simply don't have the contribution rights and the last I checked, there was a typo.

**Comment by AlanBateman** [comment]
Contributions to OpenJDK require signing the OCA. The PR and comments are otherwise in limbo and not notified to the -dev list. If this is typo someone and you aren't planning to sign the OCA then it is best to bring it to the dev list and we can fix it.

**Comment by Glusk** [comment]
@AlanBateman

The [instruction links](https://www.oracle.com/technetwork/community/oca-486395.html) link for signing the OCA is broken.

I was hoping someone else could make the pull request, like here: https://github.com/openjdk/loom/pull/22

It's only a small typo anyway.

**Comment by AlanBateman** [comment]
Closing this PR has it has been "stuck" for several months. The description suggests there is a typo somewhere but we can't look at the content to know what it is about.

**Pull request closed without merging**
