### PR TITLE
Loom: Add missing stubs to fix build failures on PPC64, S390, ARM32 and Zero

### PR DESCRIPTION
**Pull request by shqking**
PPC64, S390, ARM32, Zero stubs were initially introduced to Loom in
commit 3a89cd5 [1]. However, necessary updates were missing afterward,
leading to compilation failures.

1. frame_helpers.inline.hpp

In commit 854a81a [2], platform specific implementation was extracted
from continuation.cpp to frame_helpers.inline.hpp, and the corresponding
headers for only x86 and aarch64 were created then.

This same updates should be done to PPC64/S390/ARM32/Zero as well.
Otherwise, the following compilation error would be emitted.

```
~/jdk_src/src/hotspot/share/runtime/frame_helpers.inline.hpp:326:1:
fatal error: frame_helpers_ppc.inline.hpp: No such file or directory

  326 | #include CPU_HEADER_INLINE(frame_helpers)

        | ^~~~~~~~~~~~~~~~~

        compilation terminated.
```

Fix: see the updates in continuation_XX.inline.hpp and
frame_helpers_XX.inline.hpp.

2. ZGC support for PPC64

ZGC support for Loom was implemented two years ago in commit 05b1b53
[3]. Recently ZGC for PPC64 was supported in the mainline. See commit
337b73a [4].

However, stub `BarrierSetNMethod::arm()` is missing for PPC64 platform.

Here is the snippet of error log when cross-compiling on PPC64 in my
local test environment.

```
* For target
* hotspot_variant-server_libjvm_gtest_objs_BUILD_GTEST_LIBJVM_link:
/usr/lib/gcc-cross/powerpc64le-linux-gnu/9/../../../../powerpc64le-linux-gnu/bin/ld:
~/build-release/hotspot/variant-server/libjvm/objs/zNMethod.o:
in function `ZNMethod::arm(nmethod*, int)':
~/jdk_src/src/hotspot/share/gc/z/zNMethod.cpp:213:
undefined reference to `BarrierSetNMethod::arm(nmethod*, int)'
/usr/lib/gcc-cross/powerpc64le-linux-gnu/9/../../../../powerpc64le-linux-gnu/bin/ld:
~/jdk_src/src/hotspot/share/gc/z/zNMethod.cpp:213:
undefined reference to `BarrierSetNMethod::arm(nmethod*, int)'
collect2: error: ld returned 1 exit status
```

In this patch, we add the stub. See the update in file
barrierSetNMethod_ppc.cpp.

Testing:

Linux PPC64 cross-compilation
Linux S390 cross-compilation
Linux ARM32 cross-compilation
Linux AArch64 Zero (Hotspot) compilation
Linux x86_64 tier1_loom passes
Linux AArch64 tier1_loom passes

[1] https://github.com/openjdk/loom/commit/3a89cd5
[2] https://github.com/openjdk/loom/commit/854a81a
[3] https://github.com/openjdk/loom/commit/05b1b53
[4] https://github.com/openjdk/loom/commit/337b73a

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - no project role)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/87/head:pull/87` \
`$ git checkout pull/87`

Update a local copy of the PR: \
`$ git checkout pull/87` \
`$ git pull https://git.openjdk.java.net/loom pull/87/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 87`

View PR using the GUI difftool: \
`$ git pr show -t 87`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/87.diff">https://git.openjdk.java.net/loom/pull/87.diff</a>

</details>

### CODE REVIEW

**Comment by AlanBateman** [comment]
> PPC64, S390, ARM32, Zero stubs were initially introduced to Loom in
> commit [3a89cd5](https://github.com/openjdk/loom/commit/3a89cd5a85acca136cc3329a9b11253280435bb4) [1]. However, necessary updates were missing afterward,
> leading to compilation failures.

Our focus has been x64 and aarch64 so have been ignoring other architectures and the zero build. At a glance, your update looks okay and can be integrated. @shipilev Do you have any comments on this?

**Review by shipilev — APPROVED** [review]
Looks fine, as long as it builds Zero. GHA has Zero checks that can be used to verify this automatically.

**Review by AlanBateman — APPROVED** [review]

**Comment by shqking** [comment]
Thanks for your reviews! @AlanBateman  and @shipilev 

As suggested by @shipilev , I ran the GHA manually. See https://github.com/shqking/loom/runs/4969398407?check_suite_focus=true

Unfortunately arm32 build failed due to one compilation warning.
In my previous local testing, this warning was not exposed mainly because I tested `release` build rather than `fastdebug` build.

I will fix this warning soon.

**Review by AlanBateman — APPROVED** [review]

**Comment by shqking** [comment]
The build test in GHA passed now. See https://github.com/shqking/loom/actions/runs/1760254363

Could you please help to take a review @shipilev ? Thanks.

**Review by shipilev — APPROVED** [review]

**Comment by shqking** [comment]
Thanks a lot for your review.

/integrate

**Pull request closed without merging**
