### PR TITLE
RISC-V vthread support for JVM intrinsic monitors

### PR DESCRIPTION
**Pull request by RealFYang**
This ported vthread support for JVM intrinsic monitors to linux-riscv64 platform.

Testing on linux-riscv64:
- [x] make test TEST="hotspot_loom jdk_loom" (release & fastdebug)
- [x] make test TEST=tier1/2/3 (release)
- [x] make test TEST=hotspot:tier4 (release)

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Patricio Chilano Mateo](https://openjdk.org/census#pchilanomate) (@pchilano - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/loom.git pull/212/head:pull/212` \
`$ git checkout pull/212`

Update a local copy of the PR: \
`$ git checkout pull/212` \
`$ git pull https://git.openjdk.org/loom.git pull/212/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 212`

View PR using the GUI difftool: \
`$ git pr show -t 212`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/loom/pull/212.diff">https://git.openjdk.org/loom/pull/212.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/loom/pull/212#issuecomment-2314638453)

### CODE REVIEW

**Comment by robehn** [comment]
Nice work!

**Comment by pchilano** [comment]
Great! I see test jdk/java/lang/Thread/virtual/Parking.java should also have os.arch=="riscv64" added.

**Comment by RealFYang** [comment]
> Great! I see test jdk/java/lang/Thread/virtual/Parking.java should also have os.arch=="riscv64" added.

Thanks for finding this! Seems that I missed this test. Added and tested with both release and fastdebug builds on linux-riscv64.

**Comment by AlanBateman** [comment]
> Thanks for finding this! Seems that I missed this test somehow. Added and tested with both release and fastdebug builds on linux-riscv64.

Thanks for the update. Once all ports that support VMContinuations are aligned then I think we can drop this `@requires` and have them be selected with `@requires vm.continuations` like the other tests.

**Comment by pchilano** [comment]
Great, thanks @RealFYang!

**Comment by AlanBateman** [comment]
@RealFYang If you "/integrate" then we should be able to sponsor.

**Comment by RealFYang** [comment]
OK. Let's get this integrated. Thanks everyone for having a look.
/integrate

**Pull request closed without merging**
