### PR TITLE
Loom cleanups

### PR DESCRIPTION
**Pull request by stefank**
Various cleanups and restructuring.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Coleen Phillimore](https://openjdk.java.net/census#coleenp) (@coleenp - Committer)
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/108/head:pull/108` \
`$ git checkout pull/108`

Update a local copy of the PR: \
`$ git checkout pull/108` \
`$ git pull https://git.openjdk.java.net/loom pull/108/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 108`

View PR using the GUI difftool: \
`$ git pr show -t 108`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/108.diff">https://git.openjdk.java.net/loom/pull/108.diff</a>

</details>

### CODE REVIEW

**Review by coleenp — APPROVED** [review]
Thank you! this was one of the things I wanted most. I was reviewing the stackChunkFrameStream separation patch.

**Review by coleenp — APPROVED** [review]
Good.

**Review by fisk — APPROVED** [review]
Nice cleaup!

**Comment by stefank** [comment]
Closed, since all the changes were pushed outside of this PR.

**Pull request closed without merging**
