### PR TITLE
Loom cleanup 6

### PR DESCRIPTION
**Pull request by stefank**
More cleanups.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/135/head:pull/135` \
`$ git checkout pull/135`

Update a local copy of the PR: \
`$ git checkout pull/135` \
`$ git pull https://git.openjdk.java.net/loom pull/135/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 135`

View PR using the GUI difftool: \
`$ git pr show -t 135`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/135.diff">https://git.openjdk.java.net/loom/pull/135.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Found a seemingly incorrect comment change, otherwise good.

**Review by fisk — APPROVED** [review]

**Comment by stefank** [comment]
These changes were rebased and pushed manually to loom/fibers.

**Pull request closed without merging**
