### PR TITLE
dcubed - cleanup2 changes (JVM/TI, JDI, JDWP)

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial cleanup changes to JVM/TI, JDI and JDWP.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Chris Plummer](https://openjdk.java.net/census#cjplummer) (@plummercj - Committer)
 * [Serguei Spitsyn](https://openjdk.java.net/census#sspitsyn) (@sspitsyn - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/153/head:pull/153` \
`$ git checkout pull/153`

Update a local copy of the PR: \
`$ git checkout pull/153` \
`$ git pull https://git.openjdk.java.net/loom pull/153/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 153`

View PR using the GUI difftool: \
`$ git pr show -t 153`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/153.diff">https://git.openjdk.java.net/loom/pull/153.diff</a>

</details>

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
@plummercj - Please review when you get the chance.
@sspitsyn - The one remaining JVM/TI change is a single character delete.

**Review by plummercj — COMMENTED** [review]
Regarding the 2022 copyright changes, are we suppose to update the copyright of any file we changed, even if the change was in 2021 or earlier?

**Comment by dcubed-ojdk** [comment]
My understanding is that the copyrights are updated to year in which the changes are integrated into jdk/jdk.

**Comment by dcubed-ojdk** [comment]
In particular because when Loom integrates into jdk/jdk, the commits will be squished into a single changeset so all the history will be lost (from the jdk/jdk POV).

**Review by plummercj — APPROVED** [review]

**Review by sspitsyn — APPROVED** [review]
Looks good.
Thanks,
Serguei

**Comment by dcubed-ojdk** [comment]
@plummercj and @sspitsyn - Thanks for the reviews.

/integrate

**Comment by AlanBateman** [comment]
> Regarding the 2022 copyright changes, are we suppose to update the copyright of any file we changed, even if the change was in 2021 or earlier?

We'll do a bulk update of the copyright headers prior to integration as there are likely many files that were modified in previous years so won't have the right date for the main line.

**Pull request closed without merging**
