### PR TITLE
Fix Optimized builds

### PR DESCRIPTION
**Pull request by shipilev**
The usual trap in Hotspot code is the belief that `ASSERT <=> !PRODUCT`, but that's not actually true. You would not see this in regular release (`!ASSERT`, `PRODUCT`) or fastdebug (`ASSERT`, `!PRODUCT`) builds, but you would see it in optimized (`!ASSERT`, `!PRODUCT`) builds. See for example GHA: https://github.com/shipilev/loom/runs/3717294006?check_suite_focus=true

The use of `ASSERT` and `PRODUCT` should be consistent to avoid build failures in optimized builds.

Additional testing:
 - [x] Linux x86_64 optimized now builds
 - [x] Linux x86_64 release still builds
 - [x] Linux x86_64 fastdebug still builds

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - Committer) ⚠️ Review applies to 9070ba6a6f18bffdc1414f319081122f006bbd37

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/69/head:pull/69` \
`$ git checkout pull/69`

Update a local copy of the PR: \
`$ git checkout pull/69` \
`$ git pull https://git.openjdk.java.net/loom pull/69/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 69`

View PR using the GUI difftool: \
`$ git pr show -t 69`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/69.diff">https://git.openjdk.java.net/loom/pull/69.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Any takers?

**Review by vnkozlov — APPROVED** [review]
Seems fine to me.

**Comment by shipilev** [comment]
Thank you! @AlanBateman -- should I wait for any Loom Reviewers to ack PRs like these?

**Comment by AlanBateman** [comment]
> Thank you! @AlanBateman -- should I wait for any Loom Reviewers to ack PRs like these?

@pron, do you want to look at this?

**Comment by pron** [comment]
Can you explain this change? Why should fields and methods that only appear in assertions be guarded by !PRODUCT rather than ASSERT?

**Comment by shipilev** [comment]
> Can you explain this change? Why should fields and methods that only appear in assertions be guarded by !PRODUCT rather than ASSERT?

AFAICS, everything that is `print_*` can be used from debugging printouts, not only from asserts, so it needs to be `!PRODUCT`. I can tell more if you pick any method as the example.

**Comment by shipilev** [comment]
That said, I can rewrite all `PRODUCT` defines to `ASSERT`/`DEBUG`, if that was the intent. I think the current patch uses `!PRODUCT` and `ASSERT`/`DEBUG` inconsistently, so we can lean into one side more heavily, e.g. drop all `PRODUCT` thingies...

**Comment by shipilev** [comment]
Forgot to say this: notice that `log_develop_trace` is `!PRODUCT` rather than `ASSERT`. So if you reference a field in that logging statement, you need to either make that field `NOT_PRODUCT`, or wrap the `log_develop_trace` into `DEBUG_ONLY`. I believe `NOT_PRODUCT` is less awkward.

**Comment by shipilev** [comment]
See new commit for a bit cleaner patch. It follows the simple guideline: if a field/method is used in any tracing/printout method, it is `!PRODUCT`. The methods that are assert-only are moved to `ASSERT`.

**Comment by pron** [comment]
Ah, OK. I understand the logic now, but it means that the guard will need to be revisited once the traces are cleaned up. You can integrate. Is there a logging mode that is guarded by ASSERT (that would be the most common intent in this code)?

**Comment by shipilev** [comment]
> Ah, OK. I understand the logic now, but it means that the guard will need to be revisited once the traces are cleaned up. 

Yes.

> Is there a logging mode that is guarded by ASSERT (that would be the most common intent in this code)?

I don't think so. IIRC, the purpose of "optimized" was to dump the diagnostic output without suffering the performance loss of fastdebug, so it stands to reason why logging is `!PRODUCT`. But, it is a recurrent theme to ditch the "optimized" builds -- https://bugs.openjdk.java.net/browse/JDK-8183287 -- which should put this problem where it belongs, into the dustbin.

**Comment by shipilev** [comment]
Linux x86_64 `release`, `fastdebug`, `optimized` builds are passing in GHA.

/integrate

**Pull request closed without merging**
