### PR TITLE
Fix Windows aarch64 builds

### PR DESCRIPTION
**Pull request by shipilev**
Current GHA point the problem with Windows aarch64 builds:
  https://github.com/shipilev/loom/runs/3721167733
 
It passes now:
  https://github.com/shipilev/loom/runs/3722819426

Additional testing:
 - [x] Windows aarch64 GHA builds fine
 - [x] Linux aarch64 `tier1_loom` still passes

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - Committer) ⚠️ Review applies to 3289b95acd0f7d1403ff4803c7319bc643ebbad0

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/loom pull/70/head:pull/70` \
`$ git checkout pull/70`

Update a local copy of the PR: \
`$ git checkout pull/70` \
`$ git pull https://git.openjdk.java.net/loom pull/70/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 70`

View PR using the GUI difftool: \
`$ git pr show -t 70`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/loom/pull/70.diff">https://git.openjdk.java.net/loom/pull/70.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Any takers? :)

**Review by theRealAph — APPROVED** [review]
This is an obviously-correct fix, but if I were doing it I'd be tempted to try a size_t overload to `MacroAssembler::sub()` instead. Mind you, that would probably have side effects elsewhere.

**Comment by shipilev** [comment]
This one needs @AlanBateman and @pron ack as well, I think.

**Comment by pron** [comment]
It's fine if it builds on all platforms now.

**Comment by shipilev** [comment]
There is a macos-aarch64 build problem reported by GHA, but I think it was fixed by https://github.com/openjdk/loom/commit/1f9ab1457bc0775d8d53c23358f690fd11b1de9f. I am re-running GHA to make sure all AArch64 platforms build fine.

**Comment by shipilev** [comment]
There are still weird failures on macos-aarch64, like:

```
2021-09-30T11:41:57.9432190Z /Users/runner/work/loom/loom/jdk/src/hotspot/share/oops/accessBackend.hpp:1203:5: warning: unused typedef 'STATIC_ASSERT_DUMMY_TYPE_1205' [-Wunused-local-typedef]
2021-09-30T11:41:57.9433590Z     STATIC_ASSERT((HasDecoratoUndefined symbols for architecture x86_64:
2021-09-30T11:41:57.9434590Z   "JvmtiThreadState::set_thread(JavaThread*)", referenced from:
2021-09-30T11:41:57.9435460Z       JavaThread::rebind_to_jvmti_thread_state_of(oop) in thread.o
2021-09-30T11:41:57.9436330Z   "JvmtiVTMTDisabler::start_VTMT(_jobject*, int)", referenced from:
2021-09-30T11:41:57.9437180Z       _JVM_VirtualThreadMountBegin in jvm.o
2021-09-30T11:41:57.9438020Z       _JVM_VirtualThreadUnmountBegin in jvm.o
2021-09-30T11:41:57.9438870Z   "JvmtiVTMTDisabler::_VTMT_count", referenced from:
2021-09-30T11:41:57.9439640Z       JavaThread::set_is_VTMT_disabler(bool) in thread.o
2021-09-30T11:41:57.9440470Z   "JvmtiVTMTDisabler::finish_VTMT(_jobject*, int)", referenced from:
2021-09-30T11:41:57.9441300Z       _JVM_VirtualThreadMountEnd in jvm.o
2021-09-30T11:41:57.9442080Z       _JVM_VirtualThreadUnmountEnd in jvm.o
2021-09-30T11:41:57.9442930Z   "JvmtiVTMTDisabler::_VTMT_disable_count", referenced from:
2021-09-30T11:41:57.9443720Z       JavaThread::set_is_in_VTMT(bool) in thread.o
2021-09-30T11:41:57.9444370Z       JavaThread::java_suspend() in thread.o
2021-09-30T11:41:57.9445220Z   "JvmtiEventController::thread_started(JavaThread*)", referenced from:
2021-09-30T11:41:57.9446160Z       JavaThread::rebind_to_jvmti_thread_state_of(oop) in thread.o
2021-09-30T11:41:57.9446890Z ld: symbol(s) not found for architecture x86_64
2021-09-30T11:41:57.9448190Z clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

But I believe they are unrelated to this patch. windows-aarch64 and linux-aarch64 seem to build fine in GHA. I propose we integrate this PR, and deal with the rest later.

/integrate

**Pull request closed without merging**
